# -*- coding: utf-8 -*-
"""textgenerationcode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_QAqqxecWcbpuIS55FAhV5S4_zCcQ_l9
"""

!pip install transformers touch

from transformers import pipeline

#Load text generation model(GenAI)
generator = pipeline("text-generation",model="gpt2")

#Input prompt
prompt = "Artificial Intelligence in finance will"

#Generate text
result = generator(prompt,max_length = 50,num_return_sequences = 1)
print("AI Generator Text:")
print(result[0]['generated_text'])